# Generated by Django 3.1.3 on 2021-07-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odcinek', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sluza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('lokalizacja', models.CharField(max_length=30)),
                ('opis', models.TextField(default='')),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunk', to='mainMap.chunk')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
    ]
