# Generated by Django 3.1.3 on 2021-07-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
    ]
