# Generated by Django 3.1.3 on 2021-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0002_auto_20210714_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
