# Generated by Django 3.1.3 on 2021-07-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0003_auto_20210715_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
