# Generated by Django 3.1.3 on 2021-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0005_chunk_viewbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='background',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
