# Generated by Django 3.1.3 on 2021-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0007_auto_20210717_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
