# Generated by Django 3.1.3 on 2021-07-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0009_auto_20210717_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
