# Generated by Django 3.1.3 on 2021-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0011_auto_20210719_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
