# Generated by Django 3.1.3 on 2021-07-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0013_auto_20210719_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextChunk', to='mainMap.chunk'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevChunk', to='mainMap.chunk'),
        ),
    ]
