# Generated by Django 3.1.3 on 2021-07-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0015_jaz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jaz',
            new_name='Weir',
        ),
    ]
