# Generated by Django 3.1.3 on 2021-07-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0016_auto_20210723_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weir',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='lock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weir',
            name='description',
        ),
        migrations.AddField(
            model_name='lock',
            name='contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lock',
            name='dimensions',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lock',
            name='distance',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marina',
            name='contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marina',
            name='dimensions',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marina',
            name='distance',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weir',
            name='contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weir',
            name='dimensions',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weir',
            name='distance',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weir',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weir', to='mainMap.chunk'),
        ),
    ]
