# Generated by Django 3.2.5 on 2021-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0018_auto_20210723_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='meta',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='marina',
            name='meta',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='weir',
            name='meta',
            field=models.CharField(default='', max_length=300),
        ),
    ]
