# Generated by Django 3.1.3 on 2021-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0019_auto_20210728_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='meta',
        ),
    ]
