# Generated by Django 3.1.3 on 2021-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0020_remove_lock_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='background',
        ),
        migrations.AddField(
            model_name='chunk',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
