# Generated by Django 3.1.3 on 2021-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMap', '0021_auto_20210811_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='next',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='prev',
        ),
        migrations.AddField(
            model_name='chunk',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
