# Generated by Django 3.1.3 on 2021-08-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephoneblock',
            name='telephoneUnit',
        ),
        migrations.AddField(
            model_name='telephoneblock',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='telephoneunit',
            name='telephoneUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telephoneBlock', to='telephones.telephoneblock'),
        ),
    ]
