# Generated by Django 3.1.3 on 2021-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0002_auto_20210811_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephoneunit',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
