# Generated by Django 3.1.3 on 2021-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0004_auto_20210811_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephoneunit',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='telephoneunit',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
