# Generated by Django 3.1.3 on 2021-08-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0005_auto_20210811_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephoneunit',
            name='telephoneUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telephoneUlock', to='telephones.telephoneblock'),
        ),
    ]
